// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv1RDMydkKFNBNsknhTByb9dP2SV8ZzXQ',
    appId: '1:422602946138:android:ea31a43fdbf51a3818ca63',
    messagingSenderId: '422602946138',
    projectId: 'geogamekk',
    databaseURL: 'https://geogamekk-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'geogamekk.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhMZ1WyPKmOv1CD8ZF6tpd2tHXAkvrm6Y',
    appId: '1:422602946138:web:5a50870baba5afa718ca63',
    messagingSenderId: '422602946138',
    projectId: 'geogamekk',
    authDomain: 'geogamekk.firebaseapp.com',
    databaseURL: 'https://geogamekk-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'geogamekk.firebasestorage.app',
    measurementId: 'G-XHF4FYY8K7',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhMZ1WyPKmOv1CD8ZF6tpd2tHXAkvrm6Y',
    appId: '1:422602946138:web:591cfe5753d95d0818ca63',
    messagingSenderId: '422602946138',
    projectId: 'geogamekk',
    authDomain: 'geogamekk.firebaseapp.com',
    databaseURL: 'https://geogamekk-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'geogamekk.firebasestorage.app',
    measurementId: 'G-8TJH0F54N3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMcojqpEBfrS6i0TqzGbmR8nHTFOL7_fo',
    appId: '1:422602946138:ios:4a7bb7a7a148f1c918ca63',
    messagingSenderId: '422602946138',
    projectId: 'geogamekk',
    databaseURL: 'https://geogamekk-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'geogamekk.firebasestorage.app',
    androidClientId: '422602946138-kt9ml0a8k2r53m4o0qr5fqhn0ctmdv65.apps.googleusercontent.com',
    iosClientId: '422602946138-vqbk94ousvi1htcji4rk2d0n5gbtu23i.apps.googleusercontent.com',
    iosBundleId: 'com.kk.geogame',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMcojqpEBfrS6i0TqzGbmR8nHTFOL7_fo',
    appId: '1:422602946138:ios:4a7bb7a7a148f1c918ca63',
    messagingSenderId: '422602946138',
    projectId: 'geogamekk',
    databaseURL: 'https://geogamekk-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'geogamekk.firebasestorage.app',
    androidClientId: '422602946138-kt9ml0a8k2r53m4o0qr5fqhn0ctmdv65.apps.googleusercontent.com',
    iosClientId: '422602946138-vqbk94ousvi1htcji4rk2d0n5gbtu23i.apps.googleusercontent.com',
    iosBundleId: 'com.kk.geogame',
  );

}
