// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv1RDMydkKFNBNsknhTByb9dP2SV8ZzXQ',
    appId: '1:422602946138:android:fa1691bb3d191e5818ca63',
    messagingSenderId: '422602946138',
    projectId: 'geogamekk',
    databaseURL: 'https://geogamekk-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'geogamekk.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhMZ1WyPKmOv1CD8ZF6tpd2tHXAkvrm6Y',
    appId: '1:422602946138:web:e2a457d277b914b418ca63',
    messagingSenderId: '422602946138',
    projectId: 'geogamekk',
    authDomain: 'geogamekk.firebaseapp.com',
    databaseURL: 'https://geogamekk-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'geogamekk.firebasestorage.app',
    measurementId: 'G-K3S4B0J03W',
  );
}
